<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MuridSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('murid')->insert([
            [
                'nis' => '1001',
                'nama' => 'Andi Saputra',
                'kelas' => 'XI RPL 1',
                'telepon' => '089876543210',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-03-15',
                'username_user' => '1001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1002',
                'nama' => 'Budi Prakoso',
                'kelas' => 'XI RPL 1',
                'telepon' => '089765432109',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-06-22',
                'username_user' => '1002',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1003',
                'nama' => 'Cindy Amelia',
                'kelas' => 'XI RPL 1',
                'telepon' => '089654321098',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2006-08-19',
                'username_user' => '1003',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1004',
                'nama' => 'Deni Ramadhan',
                'kelas' => 'XI RPL 1',
                'telepon' => '089543210987',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-12-01',
                'username_user' => '1004',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1005',
                'nama' => 'Eka Putri',
                'kelas' => 'XI RPL 1',
                'telepon' => '089432109876',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2006-09-10',
                'username_user' => '1005',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1006',
                'nama' => 'Farhan Maulana',
                'kelas' => 'XI RPL 1',
                'telepon' => '089321098765',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-01-25',
                'username_user' => '1006',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1007',
                'nama' => 'Gina Rahmawati',
                'kelas' => 'XI RPL 1',
                'telepon' => '089210987654',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2006-04-17',
                'username_user' => '1007',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1008',
                'nama' => 'Hendra Saputra',
                'kelas' => 'XI RPL 1',
                'telepon' => '089109876543',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-05-06',
                'username_user' => '1008',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1009',
                'nama' => 'Indah Permata',
                'kelas' => 'XI RPL 1',
                'telepon' => '089098765432',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2006-11-29',
                'username_user' => '1009',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1010',
                'nama' => 'Joko Santoso',
                'kelas' => 'XI RPL 1',
                'telepon' => '088987654321',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-07-13',
                'username_user' => '1010',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1011',
                'nama' => 'Kevin Aditya',
                'kelas' => 'XI RPL 1',
                'telepon' => '088876543210',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-10-01',
                'username_user' => '1011',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1012',
                'nama' => 'Lilis Nuraini',
                'kelas' => 'XI RPL 1',
                'telepon' => '088765432109',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2006-02-05',
                'username_user' => '1012',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1013',
                'nama' => 'Miftah Huda',
                'kelas' => 'XI RPL 1',
                'telepon' => '088654321098',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-12-30',
                'username_user' => '1013',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1014',
                'nama' => 'Nia Lestari',
                'kelas' => 'XI RPL 1',
                'telepon' => '088543210987',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2006-03-23',
                'username_user' => '1014',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1015',
                'nama' => 'Oki Pratama',
                'kelas' => 'XI RPL 1',
                'telepon' => '088432109876',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-06-12',
                'username_user' => '1015',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1016',
                'nama' => 'Putri Ayu',
                'kelas' => 'XI RPL 2',
                'telepon' => '088321098765',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2006-08-28',
                'username_user' => '1016',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1017',
                'nama' => 'Qory Amalia',
                'kelas' => 'XI RPL 2',
                'telepon' => '088210987654',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2006-09-14',
                'username_user' => '1017',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1018',
                'nama' => 'Rian Kurniawan',
                'kelas' => 'XI RPL 2',
                'telepon' => '088109876543',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-07-07',
                'username_user' => '1018',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1019',
                'nama' => 'Sinta Wulandari',
                'kelas' => 'XI RPL 2',
                'telepon' => '088098765432',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2006-01-03',
                'username_user' => '1019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nis' => '1020',
                'nama' => 'Tegar Wahyudi',
                'kelas' => 'XI RPL 2',
                'telepon' => '087987654321',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-02-27',
                'username_user' => '1020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
